### ISSUE TITLE
Update Functionality on the buttons and validation checks

### ISSUE THREAD

**Issue by chimmykk** [chimmykk/Namada-SDK#11]
as per https://github.com/chimmykk/Namada-SDK/issues/5#issuecomment-2424866071
### Describe your changes
Improve code UI/UX Validation of input in src/

1. -[x] Validation of inputs
2. [x] When seed phrase are pasted it should auto complete the words instead of user having to input one by one (sample.html) https://github.com/chimmykk/Namada-SDK/blob/rustapp/src/importnew.html
3. [x] Validate next buttons unless their requirement are met( Applies to all input/textbox) unless requirement are met no next button must go through
4. [x] For private key (Used BIP32 or Private key format) Accept only private keys format  (importnew.html) https://github.com/chimmykk/Namada-SDK/blob/rustapp/src/importnew.html private key section.
Must only accept private key format.
5. [x] For the verify word/ seed phrase section (verifyword.html) make sure it generate random words #
(As for now it's hardcode to #2wordd and #5word) randomize it , For eg. for 12 words random.math till 1 -12 and for 24, till 1-24 https://github.com/chimmykk/Namada-SDK/blob/rustapp/src/verifyword.html
later we can have a helper.js that verify and check if that match words what was generated
6. [x] Password hide and show functionality  https://github.com/chimmykk/Namada-SDK/issues/11#issuecomment-2425127785 
7. [x]   All checks should passed

Checklist before Pull request
 - [x]  Check on LiveView
 - [x] Run on the app(Tauri), src-tauri/
- [x]  All tested and verified

**Comment by chimmykk** [comment]
maybe add one more functionality like? hide and show > supposedly like when user click on the word it should show and when move is hover out it is hidden in like 
<img width="173" alt="Screenshot 2024-10-20 at 10 36 09 PM" src="https://github.com/user-attachments/assets/e00fc72f-5720-4208-8def-b7b50dd61f20">

**Comment by chimmykk** [comment]
> maybe add one more functionality like? hide and show > supposedly like when user click on the word it should show and when move is hover out it is hidden in like <img alt="Screenshot 2024-10-20 at 10 36 09 PM" width="173" src="https://private-user-images.githubusercontent.com/53212931/378209211-e00fc72f-5720-4208-8def-b7b50dd61f20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0NDQ2NTEsIm5iZiI6MTcyOTQ0NDM1MSwicGF0aCI6Ii81MzIxMjkzMS8zNzgyMDkyMTEtZTAwZmM3MmYtNTcyMC00MjA4LThkZWYtYjdiNTBkZDYxZjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE3MTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYTNmNTkxZDY1YWM3MmU4ZGUyNzhhNTMzNDQxYmZiYWVjODc2YTkyZjc4NTNhMjE3YjAwYjdiNTBkZDdmYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2AoFm-MLWJf3xP8xUSkd0eljbmYNu03V1YQEpSeHaLw">

@suhaimz11 , just for visibility tagging

**Comment by suhaimz11** [comment]
all the issues are completed. in the verify seed phrase , its randomize but it should be validated from sample.html.

**Comment by chimmykk** [comment]
pr merge #13
