### ISSUE TITLE
Update Feat Dashboard view

### ISSUE THREAD

**Issue by chimmykk** [chimmykk/Namada-SDK#12]
### Describe your changes
Improve code UI/UX Validation of input in src/

1. [x] Create a dashboard view for wallets, Account section, Settings and other placeholder.
2.  [x] Setttings to view address, private keys and retrieve seed phrase.
3. [x] Should be able to change network rpc
4. [x] Display Balance, Transparent and shielded balance
5. [x] Integrate past transaction (maybe last 5 txn) and display
6. [x] Add a function to receive that display current address + (QR code)

Checklist before Pull request
 - [x]  Check on LiveView
 - [x] Run on the app(Tauri), src-tauri/
- [x]  All tested and verified

**Comment by chimmykk** [comment]
<img width="859" alt="Screenshot 2024-10-21 at 9 35 07 PM" src="https://github.com/user-attachments/assets/72c3b0c3-7b44-4189-9295-076d5bbc7720">
<img width="859" alt="Screenshot 2024-10-21 at 9 35 29 PM" src="https://github.com/user-attachments/assets/826e9b64-6860-4994-9527-92457dcba005">
So, yeah have some thing like this dashboard>

Exchange not necessarily needed, receive and sell, where it redirect to existing
 
On the sidebar BTC TO NAM maybe?

Under settings
 Have like change network rpc section
Wallets (If they want to change what wallet they want to use? maybe come up with an idea, > like metamask has on top where user can select which wallet to use?
Address books - that has list of address
Security and backup - for checking 

Supports 



Etc , that should look like a crypto wallet in basic( Setttings to view address, private keys and retrieve seed phrase.)

**Comment by chimmykk** [comment]
https://github.com/user-attachments/assets/0fa69ee2-854f-43bb-b202-96cc8dc699a8

So yeah, since basic html doesn't support component playaround we will use js<>to dynamically render the html pages, so that it doesn't href or window.href over to a new page. So there maybe conflicts on buttons and css when trying to import for  sendtoken/receivetoken. Feel free to update the div class of button to something unique, so that it won't conflict the existing button structure,  @suhaimz11 just tagging for visibility!

**Comment by chimmykk** [comment]
Working parallel along side here, so we can push it further more

Assigned yourself with  @(username) with what you're currently working on (as it can cause conflict of double work)
1. [x] Connection & Sync @chimmykk (working on it)
2. [x] Wallets
3. [x] Address Book @chimmykk (working on it)
4. [x] Security and Backup
5. [x] Privacy
6. [x] Maybe get rid of Display settings & Other settings
7. [x] Support as default (Some like contact us at @namazo.co)

**Comment by suhaimz11** [comment]
use this code for your coonection and sync work

**Comment by chimmykk** [comment]
<img width="492" alt="Screenshot 2024-10-24 at 5 19 52 PM" src="https://github.com/user-attachments/assets/368c95f6-0fb6-4312-81fe-264f9fcb9187">
<br>
The above for connection and Sync & add one more button on the adjacent, as(Turn Shielded sync)
<img width="822" alt="Screenshot 2024-10-24 at 5 20 24 PM" src="https://github.com/user-attachments/assets/4a32e4b7-3f3d-413f-bd45-d36a675291a7">

<br> 
**for security and privacy its a function that reveals user wallet seed phrase**
<img width="884" alt="Screenshot 2024-10-24 at 5 20 57 PM" src="https://github.com/user-attachments/assets/b8c39638-6ab2-4e6f-9b82-fe69278eb1b8">

**so yeah this one**


<img width="307" alt="Screenshot 2024-10-24 at 5 22 03 PM" src="https://github.com/user-attachments/assets/d007ef4e-253d-452b-89ab-a4d0ae8b1942">

**above for add accounts**

**Comment by chimmykk** [comment]
The above  doesn’t necessarily mean it should match the context , but it should have the attributes that are required and serve a purpose ,
for instance, not meaning you should copy the same wallet display or add function it can simple as a textbox with basic ui/ux and add button and down the line for display maybe a list of address horizontally !

**Comment by suhaimz11** [comment]
the basic skeleton is done, now need to add functionality to all .

**Comment by chimmykk** [comment]
okay will close the issue once the basic ui/ux match as decided!

**Comment by chimmykk** [comment]
@suhaimz11 thing's have been due need this to pull ASAP! when can i expect?

**Comment by chimmykk** [comment]
good to close this as latest pr merge !

**Comment by suhaimz11** [comment]
waiting for new issue.
