### ISSUE TITLE
Fix UI/UX

### ISSUE THREAD

**Issue by chimmykk** [chimmykk/Namada-SDK#5]
### Describe your changes
Improve code UI/UX in src/

1. -[x]  Back Button should work
2. [x] The Progress (Dotted) Should navigate
3. [x] Add new Section, Wallet Name (Possibly like this)
<img width="716" alt="Screenshot 2024-10-20 at 12 18 49 AM" src="https://github.com/user-attachments/assets/a38105f5-a98a-426f-b84e-f381c2a294dc">

Checklist before Pull request
 - [x]  Check on LiveView
 - [x] Run on the app(Tauri), src-tauri/
- [x]  All tested and verified

**Comment by suhaimz11** [comment]
page 5 clipboard placement isuue. Next button shouldnt be enabled always . Proper functioning of step nav.

**Comment by chimmykk** [comment]
> page 5 clipboard placement isuue. Next button shouldnt be enabled always . Proper functioning of step nav.

yeah understood, validation checks and everything will come on next phase on development
